### ISSUE TITLE
Allow users to clock in to work when they are at a specified location

### ISSUE THREAD

**Issue by NoJuanNobody** [NoJuanNobody/homeHealthAid#2]
## User Story
 as a home health aid worker, I want the ability to clock in when I arrive at the specified home in which I wish to give aid.
 
 ## Description Details
This will involve the following sub tasks
- [x] create a home health aid user type #14 
- [x] integrate google maps api #10 
- [ ] show a map of the users location and the home where they will be working #10 
- [ ] add a clock in button which tracks the time and location of the user
- [ ] patients need to have an address stored in order for the maps api to track how far a home aid worker is when they clock in.
